### ISSUE TITLE
Configure Autobuild + CI

### ISSUE THREAD

**Issue by klokan** [moravianlibrary/AlephClipboard#1]
Setup autobuild and continuous integration a la Travis for this project.
It can be done for free at: http://www.appveyor.com/

Ideally we should have also automatically compiled release binaries in GitHub release.
See: http://www.appveyor.com/docs/deployment/github

This has been discussed in email on Jan 27.

**Comment by dudaerich** [comment]
Done. See https://ci.appveyor.com/project/moravianlibrary/alephclipboard

**Comment by klokan** [comment]
Great!

Could the system be configured with the appveyor.yml?

It is perfect that it runs - but it is important to know HOW IT WAS DONE - and how can the settings be changed by somebody else then you...

Please provide at least basic documentation - and if possible commit the settings of the build system into the repo, instead of only configuring the external system (if this is how AppVeyor runs). The knowledge you have gained about the autobuild system should be transferred to people as well. Thank you!

**Comment by dudaerich** [comment]
The appveyor.yml file was added into repository.

The default behavior of AppVeyor.com is that if the appveyor.yml file exists in the root of the project, settings from this file are used. Creating new project in AppVeyor.com is straightforward. You just click to create new project and then you can choose one from githubs project (or other provider). All webhooks are set up automatically to build project when someone push new commits into the repo. Deployment settings can be done via appveyor.yml file.

appveyor.yml

``` yaml
version: 1.0.{build}
configuration: Release
build:
  project: ALEPH Clipboard.sln
  verbosity: minimal
artifacts:
- path: bin\Release\ALEPHClipboard.exe
deploy:
- provider: GitHub
  auth_token:
    secure: p2fb5iahwUpzeg6hxOFW8ijRUs14PoLXPL7tBNhfpjIgcio4MhKRhJHUGNitQZg0 
  artifact: bin\Release\ALEPHClipboard.exe
```
- version - version of the build, the {build} variable is automatically increment at each new build
- configuration - configuration used for building
- build
  - project - path to Visual studio solution file
  - verbosity - argument for ms compiler
- artifacts - output of a build, these files can be downloaded from https://ci.appveyor.com/project/moravianlibrary/alephclipboard/build/artifacts
  - path - path to a file which will be packed and can be downloaded
- deploy - see http://www.appveyor.com/docs/deployment/github
  - auth_token
    - secure - token generated by https://github.com/settings/tokens and encrypted by https://ci.appveyor.com/tools/encrypt
  - artifact - file which will be uploaded to a Github release
